# HTTP
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# Desabilitar datasource (ainda sem banco)
quarkus.datasource.active=false

# JWT Configuration
mp.jwt.verify.publickey.location=keys/publicKey.pem
smallrye.jwt.sign.key.location=keys/privateKey.pem
mp.jwt.verify.issuer=auth-api

# Log
quarkus.log.level=INFO